#:schema node_modules/wrangler/config-schema.json
name = "cloud-ping"
main = "src/index.ts"
compatibility_date = "2024-05-12"
compatibility_flags = ["nodejs_compat"]
logpush = true

kv_namespaces = [
    { binding = "LATENCIES_STORE", id = "9edd7eae1344433caa01cc693fb29453" }
]

[observability]
enabled = true

[triggers]
crons = ["*/10 * * * *"]

tail_consumers = [{service = "cloud-ping"}]